# NOTE: update this with your service name
service: moonmail-delivery

# Use the serverless-webpack plugin to transpile ES6
plugins:
  - serverless-webpack
  - serverless-offline
  - serverless-step-functions
  - serverless-pseudo-parameters

custom:
  webpack:
    webpackConfig: ./webpack.config.js
    includeModules: true

provider:
  name: aws
  profile: ${opt:profile}
  runtime: nodejs8.10
  stage: ${opt:stage}
  region: ${opt:region}
  iamRoleStatements:
    - Effect: Allow
      Action:
        - dynamodb:*
        - ses:*
      Resource: "*"

stepFunctions:
  stateMachines:
  # Data gathering - gets data and returns only what's needed
    dataGathering:
      definition:
        Comment: "Gets all the data necessary to the delivery process"
        StartAt: GetCampaign
        States:
          GetCampaign:
            Type: Task
            Resource: "arn:aws:lambda:#{AWS::Region}:#{AWS::AccountId}:function:${self:service}-${opt:stage}-getCampaign"
            ResultPath: "$.campaign"
            Next: GetUser
          GetUser:
            Type: Task
            Resource: "arn:aws:lambda:#{AWS::Region}:#{AWS::AccountId}:function:${self:service}-${opt:stage}-getUser"
            ResultPath: "$.user"
            Next: GetList
          GetList:
            Type: Task
            Resource: "arn:aws:lambda:#{AWS::Region}:#{AWS::AccountId}:function:${self:service}-${opt:stage}-getList"
            ResultPath: "$.list"
            Next: CheckTotalRecipients
          OrganizeData:
             Type: Task
             Resource: "arn:aws:lambda:#{AWS::Region}:#{AWS::AccountId}:function:${self:service}-${opt:stage}-organizeData"
             ResultPath: "$."
             End: true
  # Data checks
    dataVerifier:
      definition: "Checks all the data and reject anything out of place"
          VerifyUserPlanLimits:
            Type: Task
            Resource: "arn:aws:lambda:#{AWS::Region}:#{AWS::AccountId}:function:${self:service}-${opt:stage}-verifyUserPlanLimits"
            ResultPath: "$.planLimits"
            Next: CheckTotalRecipients
          VerifyUserPlan:
            Type: Choice
            - Variable: "$.planLimits.status"
              StringEquals: "passed"
              Next: PlanPassed
            - Variable: "$.planLimits.status"
              StringEquals: "rejected"
              Next: PlanRejected
            default: PlanRejected
          PlanPassed:
            Type: Pass
            Next: VerifyUserScore
          PlanRejected:
            Type: Pass
            Next: NotifyUser
          NotifyUser:
            Type: Task
            Resource: "arn:aws:lambda:#{AWS::Region}:#{AWS::AccountId}:function:${self:service}-${opt:stage}-notifyUser"
            End: true
          VerifyUserScore:
            Type: Choice
            Choices: 
            - Variable: "$.reputationData.reputation"
              NumericLessThanEquals: 15
              Next: SetBlockedScore
            - And:
              - Variable: "$.reputationData.reputation"
                NumericGreaterThan: 15
              - Variable: "$.reputationData.reputation"
                NumericLessThanEquals: 30
              Next: SetBadScore
            - And:
              - Variable: "$.reputationData.reputation"
                NumericGreaterThan: 30
              - Variable: "$.reputationData.reputation"
                NumericLessThanEquals: 50
              Next: SetLowScore
            - And:
              - Variable: "$.reputationData.reputation"
                NumericGreaterThan: 50
              - Variable: "$.reputationData.reputation"
                NumericLessThanEquals: 75
              Next: SetMediumScore
            - Variable: "$.reputationData.reputation"
              NumericGreaterThan: 75
              Next: SetHighScore
          SetBlockedScore:
            Type: Pass
            Result: "lesser15"
            ResultPath: "$.sendingInfo.scoreProfile"
            Next: NotifyUser
          SetBadScore:
            Type: Pass
            Result: "bigger15Lesser30"
            ResultPath: "$.sendingInfo.scoreProfile"
            Next: NotifyUser
          SetLowScore:
            Type: Pass
            Result: "bigger30Lesser50"
            ResultPath: "$.sendingInfo.scoreProfile"
            Next: NotifyUser
          SetMediumScore:
            Type: Pass
            Result: "bigger50Lesser75"
            ResultPath: "$.sendingInfo.scoreProfile"
            Next: NotifyUser
          SetHighScore:
            Type: Pass
            Result: "bigger75"
            ResultPath: "$.sendingInfo.scoreProfile"
            Next: NotifyUser
 
functions:
  getCampaign:
    handler: handler.getCampaign
  getUser:
    handler: handler.getUser
  getList:
    handler: handler.getList
  organizeData:
    handler: handler.organizeData

  verifyUserPlanLimits:
    handler: handler.verifyUserPlanLimits
  notifyUser:
    handler: handler.notifyUser